### ISSUE TITLE
displaying nametags for pets

### ISSUE THREAD

**Issue by mkaldk** [en0tuk/eHideTags#10]
if you name any mob with a tag and then tame it, then its tag will not be displayed. I checked and the problem is in this plugin, this problem is also present in other plugins of this type, is it possible to fix it?

**Comment by en0tuk** [comment]
I will try to reproduce and fix

**Comment by en0tuk** [comment]
@mkaldk There's two ways to fix
First way: using NMS and packets  (I don't know how to work with packets)
Second way: return pet name in actionbar on right click

I will use second way to fix

**Comment by mkaldk** [comment]
Good! I'll be waiting for you to do it, thank you!!

**Comment by en0tuk** [comment]
Check Latest Release
