### ISSUE TITLE
Пишет null при нажатии на игрока

### ISSUE THREAD

**Issue by mxrcury666** [en0tuk/eHideTags#11]
На версии 1.19 пишет null когда нажимаешь на игрока. В консоли ничего не пишет

**Comment by en0tuk** [comment]
Какая версия плагина?
Какие на сервере стоят плагины?
Какую строку ты используешь для показа ника

**Comment by mxrcury666** [comment]
версия плагина 1.7.3.

![image](https://user-images.githubusercontent.com/119013824/205078419-a624fe53-c3b2-4db9-bfbc-26d3ba753bb8.png)
![image](https://user-images.githubusercontent.com/119013824/205078488-d5053b68-6f51-4760-9630-d562439d1cbf.png)

![image](https://user-images.githubusercontent.com/119013824/205078699-8ea7c748-408c-4e9a-8d87-ea91e6f9bdb1.png)

**Comment by mxrcury666** [comment]
может  не установил дополнительно что-то?

**Comment by en0tuk** [comment]
> может  не установил дополнительно что-то?
> 

А можете ли Вы попробовать использовать %displayname% за место %name% в поле message?

**Comment by mxrcury666** [comment]
пробовал, не помогает

**Comment by mxrcury666** [comment]
![sdf](https://user-images.githubusercontent.com/119013824/205337958-6f898a1a-642a-4bcf-9622-b6db89d8497b.png)

**Comment by mxrcury666** [comment]
я не установил PlaceholderAPI. Проблема решена
