### ISSUE TITLE
TAB

### ISSUE THREAD

**Issue by Vadokk** [en0tuk/eHideTags#20]
hello!  There was a bug in the rHideTags plugin - the TAB plugin interfered with hiding the nickname, does it have this problem?

**Comment by en0tuk** [comment]
> hello! There was a bug in the rHideTags plugin - the TAB plugin interfered with hiding the nickname, does it have this problem?

https://github.com/en0tuk/eHideTags#conflicts

**Comment by Vadokk** [comment]
> > Привет! Был баг в плагине rHideTags - плагин TAB мешал скрывать никнейм, у него такая проблема?
> 
> https://github.com/en0tuk/eHideTags#conflicts

Ohh, sorry, I did not see, thank you

**Comment by Vadokk** [comment]
.
