### ISSUE TITLE
Nametags not hided

### ISSUE THREAD

**Issue by MaxJFG** [en0tuk/eHideTags#3]
[19:26:56] [Server thread/INFO]: [eHideTags] Enabling eHideTags v1.6
[19:26:56] [Server thread/INFO]: 
[19:26:56] [Server thread/INFO]: eHideTags | Successfully enabled
[19:26:56] [Server thread/INFO]: eHideTags | By: vk.com/rogablik
[19:26:56] [Server thread/INFO]: 

PlugIn is enabled, but no Nametags hided.

**Comment by en0tuk** [comment]
Test plugin without other plugins

**Comment by en0tuk** [comment]
I think you have some special case because everything works for other people

https://bstats.org/plugin/bukkit/eHideTags/13770#minecraftVersion

**Comment by MaxJFG** [comment]
Which Plugin?

**Comment by en0tuk** [comment]
> Which Plugin?

eHideTags

**Comment by lynrayy** [comment]
TAB on Bungee is messing with nickname

**Comment by en0tuk** [comment]
> TAB on Bungee is messing with nickname

@lynrayy Try to enable nametag invisibility in TAB config like on spigot

**Comment by Vadokk** [comment]
> > TAB на Bungee балуется с никнеймом
> 
> @lynrayyПопробуйте включить невидимость тега имени в конфигурации TAB, например, на кране.

 how to do it?
