### ISSUE TITLE
Не показывает свое содержимое Placeholder 

### ISSUE THREAD

**Issue by Nextler** [en0tuk/eHideTags#4]
Проблема заключается в том, что любые Placeholders, которые показывают информацию из базы данных о игроках просто не работают на NPC, когда кликаю на NPC, то появляется сам заполнитель по типу: %lands_land_name%,  а не стандартное название поселения. Прошу сделать интеграцию с Citizens2, чтобы при клике на них не показыаалось ничего в ActionBar.

**Comment by en0tuk** [comment]
Их значит оно как игрока берет, буду думать как чинить и в ближайшее время пофикшу

**Comment by en0tuk** [comment]
> Проблема заключается в том, что любые Placeholders, которые показывают информацию из базы данных о игроках просто не работают на NPC, когда кликаю на NPC, то появляется сам заполнитель по типу: %lands_land_name%, а не стандартное название поселения. Прошу сделать интеграцию с Citizens2, чтобы при клике на них не показыаалось ничего в ActionBar.

Все, проверяй, если все нормально работает и у тебя, то я закрою
https://www.spigotmc.org/resources/ehidetags.97904/update?update=444429

**Comment by Nextler** [comment]
Хорошо, спасибо большое. Как буду дома, то гляну

**Comment by Nextler** [comment]
Все работает как нужно
