### ISSUE TITLE
Не отображается ник по ПКМ.

### ISSUE THREAD

**Issue by Cyberus0** [en0tuk/eHideTags#6]
В конфиге указано:
message: '%player_displayname%' В теории это должно выдавать ник игрока, а в итоге плагин выдаёт саму команду
![2022-02-10_21 03 36](https://user-images.githubusercontent.com/89688697/153469035-47d809f4-4322-4327-8791-e824df1b9e5f.png)

**Comment by en0tuk** [comment]
Есть ли другие какие-то плагины

**Comment by Cyberus0** [comment]
Есть Плейсхолдеры, они могут помешать?

**Comment by Cyberus0** [comment]
https://www.spigotmc.org/resources/rgbplaceholders-%E2%9C%A8-use-hex-colors-anywhere-%E2%AD%90-no-setup-%E2%9C%85-placeholderapi-expansion-%E2%98%84%EF%B8%8F-gradients-%E2%98%91%EF%B8%8F.88377/
Вот этот плейсхолдер

**Comment by en0tuk** [comment]
Ядро, версия, версия джавы

**Comment by Cyberus0** [comment]
purpur 1.18.1, 17

**Comment by en0tuk** [comment]
> Нет, мне будет это проблематично сделать

Ок, скинь пожалуйста строчку сообщения

**Comment by Cyberus0** [comment]
Ведь чтобы протестить нужен игрок на сервере

**Comment by Cyberus0** [comment]
actionbar:
  enabled: true
  message: '%player_displayname%'

**Comment by en0tuk** [comment]
> actionbar: enabled: true message: '%player_displayname%'

Тоесть ты не используешь RGBPlaceholders в строчке, так, надо подумать

**Comment by Cyberus0** [comment]
Да, не использую

**Comment by Cyberus0** [comment]
Вроде нет

**Comment by en0tuk** [comment]
> Вроде нет

Вставь логи на сайт https://mclo.gs и скинь мне ссылку на логи

**Comment by Cyberus0** [comment]
![image](https://user-images.githubusercontent.com/89688697/153471718-a1c59faf-a512-44c2-9137-0970f99f10bc.png)

**Comment by Cyberus0** [comment]
> > Вроде нет
> 
> Вставь логи на сайт https://mclo.gs и скинь мне ссылку на логи

А они есть в каком-то текстовом файле логов?

**Comment by Cyberus0** [comment]
Как их все скопировать если я запускаю сервер через патти с вдски

**Comment by en0tuk** [comment]
> Как их все скопировать если я запускаю сервер через патти с вдски

в корневой папке сервера есть папка logs, в ней хранятся логи

**Comment by Cyberus0** [comment]
https://mclo.gs/gAyuxG4

**Comment by en0tuk** [comment]
Хммм, не получается эмулировать данную ошибку

**Comment by Cyberus0** [comment]
Эх, придётся юзать rHideTags

**Comment by Cyberus0** [comment]
Не понял, что "оно"?
