### ISSUE TITLE
After logging in to the server, it stops working

### ISSUE THREAD

**Issue by Corner324** [en0tuk/eHideTags#8]
At first everything works, but after logging in to the server, I see the nicknames of other players, they don't see mine until they themselves re-enter. /eht reload doesn't help, only plugman reload

**Comment by Corner324** [comment]
There is no TAB on the server

**Comment by Corner324** [comment]
1.16.5 spigot

**Comment by en0tuk** [comment]
Is there any errors in console?

**Comment by en0tuk** [comment]
@Corner324 
Try latest version from Actions

[Link](https://github.com/en0tuk/eHideTags/suites/8413347166/artifacts/372195807)
